## Importing Libraries & Dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
plt.style.use('fivethirtyeight')
sns.set_style('whitegrid')

In [4]:
lead=pd.read_csv("data/Leads1.csv")
lead.head()

,id,date_of_last_request,buyer,seller,best_time_to_call,budget,created_at,updated_at,user_id,location,...,area_id,compound_id,developer_id,meeting_flag,do_not_call,lead_type_id,customer_id,method_of_contact,lead_source,campaign
0,9815,9/7/2018 0:00,True,False,"All day , any day",NaN,9/7/2018 15:58,1/24/2024 15:07,2942.0,Coast 82,...,3.0,170.0,NaN,NaN,False,1,22785,form adwords,google,google_cpc
1,90225,5/4/2022 19:59,True,False,NaN,NaN,5/4/2022 19:59,1/10/2024 13:10,1494.0,The Waterway North Coast,...,NaN,NaN,NaN,NaN,False,1,172065,generic form,google,dev_-_equity
2,198759,3/22/2023 5:23,True,False,NaN,NaN,3/22/2023 5:23,2/7/2024 15:45,4043.0,Silversands,...,NaN,NaN,NaN,NaN,False,1,192904,whatsapp,google website,NaN
3,164130,12/14/2022 0:59,True,False,NaN,NaN,12/14/2022 0:51,1/15/2024 14:38,3805.0,Fouka Bay,...,NaN,NaN,NaN,NaN,False,1,112217,facebook,facebook,(none)
4,395907,1/20/2024 17:57,True,False,NaN,NaN,1/20/2024 17:57,1/22/2024 14:58,4003.0,Golden Eagle,...,NaN,NaN,NaN,NaN,False,1,383990,facebook,facebook,madinet nasr for housing and development - lea...

In [5]:
sale=pd.read_csv("data/Sales1.csv")
sale.head()

,id,lead_id,unit_value,unit_location,expected_value,actual_value,date_of_reservation,reservation_update_date,date_of_contraction,property_type_id,area_id,compound_id,sale_category,years_of_payment
0,11218,130316,17770000.0,New Cairo,NaN,17777000.0,1/10/2024 0:00,1/10/2024 20:21,2/8/2024 0:00,21.0,2.0,345.0,Primary,8.0
1,776,32565,648000.0,New Capital City,NaN,NaN,4/11/2021 0:00,NaN,NaN,8.0,9.0,464.0,NaN,NaN
2,3016,20428,8912000.0,6th October,NaN,8912000.0,9/4/2022 0:00,9/5/2022 0:00,10/23/2022 0:00,1.0,1.0,402.0,Primary,NaN
3,9305,312091,3658000.0,Mostakbal City,NaN,3658000.0,10/12/2023 0:00,NaN,10/12/2023 0:00,13.0,10.0,908.0,Developer Commercial Sale,10.0
4,11885,173993,NaN,New Cairo,10000000.0,NaN,NaN,NaN,NaN,21.0,2.0,1116.0,NaN,NaN

In [6]:
property_type=pd.read_csv("data/property_type1.csv")
property_type.head()

     id       property_type
0  10.0              Retail
1  13.0              Clinic
2  20.0  Serviced Apartment
3  21.0           Apartment
4  11.0               Cabin

In [7]:
lead_type=pd.read_csv("data/lead_type1.csv")
lead_type.head()

     id     lead_type
0   1.0       Primary
1   3.0  Resale Buyer
2   4.0      Company Now
3   2.0        Seller
4  67.0     Brokerage

In [8]:
property_type

      id       property_type
0   10.0              Retail
1   13.0              Clinic
2   20.0  Serviced Apartment
3   21.0           Apartment
4   11.0               Cabin
..   ...                 ...
94   NaN                 NaN
95   NaN                 NaN
96   NaN                 NaN
97   NaN                 NaN
98   NaN                 NaN

[99 rows x 2 columns]

## Data Inspection

In [9]:
# check if there is duplicated rows in lead and sale dataframes
duplicate_lead_row= lead[lead.duplicated()]
duplicate_lead_row.head()

,id,date_of_last_request,buyer,seller,best_time_to_call,budget,created_at,updated_at,user_id,location,...,area_id,compound_id,developer_id,meeting_flag,do_not_call,lead_type_id,customer_id,method_of_contact,lead_source,campaign
2832,214418,5/23/2023 9:08,True,False,NaN,NaN,5/1/2023 9:09,10/22/2023 11:26,2051.0,Company Partners,...,NaN,NaN,NaN,NaN,False,1,208284,company partners form,company partners form,(none)
3799,214418,5/23/2023 9:08,True,False,NaN,NaN,5/1/2023 9:09,10/22/2023 11:26,2051.0,Company Partners,...,NaN,NaN,NaN,NaN,False,1,208284,company partners form,company partners form,(none)
7968,55664,10/4/2023 12:57,True,False,NaN,NaN,10/17/2021 20:06,1/31/2024 18:08,351.0,La Vista City,...,NaN,NaN,NaN,NaN,False,1,135742,facebook,facebook,la vista developments - lead generation - cooi...
8009,192599,3/2/2023 9:09,True,False,NaN,NaN,3/2/2023 9:10,9/24/2023 14:27,1722.0,NaN,...,NaN,NaN,NaN,NaN,False,1,186865,personal,personal,NaN
8656,214418,5/23/2023 9:08,True,False,NaN,NaN,5/1/2023 9:09,10/22/2023 11:26,2051.0,Company Partners,...,NaN,NaN,NaN,NaN,False,1,208284,company partners form,company partners form,(none)

In [10]:
# found that no duplicated rows in sale df
duplicate_sale_row= sale[sale.duplicated()]
duplicate_sale_row

Empty DataFrame
Columns: [id, lead_id, unit_value, unit_location, expected_value, actual_value, date_of_reservation, reservation_update_date, date_of_contraction, property_type_id, area_id, compound_id, sale_category, years_of_payment]
Index: []

In [11]:
# making sure that other df don't have duplicated rows
# found duplicated nans
duplicate_property_type_row= property_type[property_type.duplicated()]
duplicate_property_type_row

    id property_type
15 NaN           NaN
16 NaN           NaN
17 NaN           NaN
18 NaN           NaN
19 NaN           NaN
..  ..           ...
94 NaN           NaN
95 NaN           NaN
96 NaN           NaN
97 NaN           NaN
98 NaN           NaN

[84 rows x 2 columns]

In [12]:
# found duplicated nans
duplicate_lead_type_row= lead_type[lead_type.duplicated()]
duplicate_lead_type_row

    id lead_type
11 NaN       NaN
12 NaN       NaN
13 NaN       NaN
14 NaN       NaN
15 NaN       NaN
..  ..       ...
94 NaN       NaN
95 NaN       NaN
96 NaN       NaN
97 NaN       NaN
98 NaN       NaN

[88 rows x 2 columns]

In [13]:
lead.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55924 entries, 0 to 55923
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    55924 non-null  int64
 1   date_of_last_request  55924 non-null  object
 2   buyer                 55924 non-null  bool
 3   seller                55924 non-null  bool
 4   best_time_to_call     1528 non-null   object
 5   budget                393 non-null    float64
 6   created_at            55924 non-null  object
 7   updated_at            55924 non-null  object
 8   user_id               51288 non-null  float64
 9   location              48345 non-null  object
 10  date_of_last_contact  55593 non-null  object
 11  status_name           55924 non-null  object
 12  commercial            55924 non-null  bool
 13  merged                10933 non-null  object
 14  area_id               2073 non-null   float64
 15  compound_id           1804 non-null   float64
 16  developer_id          89 non-null     float64
 17  meeting_flag          532 non-null    float64
 18  do_not_call           55924 non-null  bool
 19  lead_type_id          55924 non-null  int64
 20  customer_id           55924 non-null  int64
 21  method_of_contact     55924 non-null  object
 22  lead_source           55674 non-null  object
 23  campaign              39565 non-null  object
dtypes: bool(4), float64(6), int64(3), object(11)
memory usage: 8.7+ MB

In [14]:
sale.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2194 entries, 0 to 2193
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       2194 non-null   int64
 1   lead_id                  2194 non-null   int64
 2   unit_value               1530 non-null   float64
 3   unit_location            1963 non-null   object
 4   expected_value           1126 non-null   float64
 5   actual_value             868 non-null    float64
 6   date_of_reservation      1454 non-null   object
 7   reservation_update_date  562 non-null    object
 8   date_of_contraction      1340 non-null   object
 9   property_type_id         1574 non-null   float64
 10  area_id                  2016 non-null   float64
 11  compound_id              1966 non-null   float64
 12  sale_category            1366 non-null   object
 13  years_of_payment         894 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 240.1+ KB

In [15]:
property_type.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             14 non-null     float64
 1   property_type  14 non-null     object
dtypes: float64(1), object(1)
memory usage: 1.7+ KB

In [16]:
lead_type.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10 non-null     float64
 1   lead_type  10 non-null     object
dtypes: float64(1), object(1)
memory usage: 1.7+ KB

## Data Pre-porcessing

In [17]:
#first drop all duplicated rows
lead=lead.drop_duplicates()

In [18]:
property_type=property_type.drop_duplicates()

In [19]:
# for making sure we run the code of finding duplicate rows again and it should have empty dfs
lead_type=lead_type.drop_duplicates()

### cleaning phase

In [20]:
for column in lead.columns:
    print(f"{column} : {lead[column].unique()}")
    print("====================================")

id : [  9815  90225 198759 ...   2233 178003 158781]
====================================
date_of_last_request : ['9/7/2018 0:00' '5/4/2022 19:59' '3/22/2023 5:23' ... '2/4/2022 22:50'
 '1/22/2023 7:13' '12/4/2022 10:12']
====================================
buyer : [ True False]
====================================
seller : [False  True]
====================================
best_time_to_call : ['All day , any day' nan '12 o’clock ' 'Evenings from 7 to 12 pm '
 '13-11-2023, 9:45 PM' 'from 3pm till 9pm' 'After 7:00 pm'
 'from  12 noon ' '12:00 PM' '12-12-2023, 6:00 PM' 'After 3.00 pm'
 'any time' 'Aftar 3' '4pm GMT ' '12:00PM' '1:00 PM' 'All day'
 'Before 6pm' '5:00 PM' 'From 11 am to 11 pm' 'Evening '
 '05-01-2024, 9:23 PM' '08-11-2023, 4:52 AM'
 'From 6-7pm daily except friday and saturday' 'Weekends' 'noon to 5pm'
 'after 5 pm UAE timing' 'Early afternoon ' 'after 7 pm '
 'من التاسعه للعاشره صباحاً' 'morning' '3:00 PM' 'Morning 12noon' '9am'
 'Any' '12am -5pm' '1:30 PM' '11:00 AM' '6pm ' '9 p.m' 'In the morning'
 'From 9:00 AM till 6 PM' 'After 5 pm' 'Any time' 'now'
 'around 11-12 noon local time' 'Evening' '01:00PM' 'Afteraf' 'After Noon'
 '1-6-2023, 8:30 PM' '7:00 PM' '10 Am to 4pm'
 'After Sunday 18/08/2019 @ 06:00 pm' '12:30 PM' '03-01-2024, 8:21 PM'
 'after 4 pm' '8:30 PM' '2-7-2023, 8:00 PM' 'Today anytime' '02:00PM'
 'Noon' '5-Dec' 'Night time ' 'Afternoon' 'weekends' '2' 'Afternoon '
 '16-12-2023, 12:07 PM' 'Monday 15th of July’19 ' 'Anytime' 'Morning '
 '24/7' '7-Nov' '2:00 PM' 'after 6 pm' '20:00' '08-10-2023, 11:55 PM'
 'after 2:00 pm daily' 'من الخامسه مساءا' 'Any time After 3:00 pm '
 '05-01-2024, 10:05 PM' '11:00AM' 'After 5pm' '5:00-9:00 pm' '21-7-2022, '
 '6pm to 8pm egypt time' 'At morning' '8:00 PM' 'Any time '
 'الساعه 10 صباحا' '18-11-2023, 7:38 PM' 'During the evenings '
 '06-11-2023, 1:33 PM' 'Between 12 pm till 5 pm ' 'Tomorrow 5 pm'
 'Ssturday afternoon' 'اي وقت ' '26-11-2022, 2:00 PM' 'tomorow afternoon'
 '6pm' 'asked to be contacted on 8:00-9:00 pm Egyptian time ' 'anytime'
 '1pm' '11am' '2:30 PM' '21-12-2023, 12:58 AM' '02-01-2024, 7:50 PM'
 'After 2:00 pm' 'all time' 'Tonight' '4:30 PM' '08-02-2024, 9:34 PM'
 'after 11 am' '02-12-2023, 3:16 PM' '9:00 PM' 'From 2 to 4'
 'اى وقت بعد ١١ ص' 'After noon ' '6:00 PM' 'Anytine between 5-9 pm' '.'
 '11 A.M - 6 P.M' '9 Am to 10 PM' '4-7-2023, 12:00 PM' '10 AM - 9 PM'
 '29-12-2023, 2:05 PM' '4pm/7pm' 'Any day around 1:00 uk time ' '4:00 PM'
 '05-11-2023, 10:25 AM' 'All' '06-11-2023, 3:17 AM' 'Thanks '
 '9am - 5 pm ' 'Sunday 15 April , 11 am - 2pm ' '10pm-11pm'
 'Any day ......... 10:00am - 7:00pm' 'At 10 aclock' '08-01-2024, 5:33 PM'
 'اليوم' 'After 7 pm' 'from 11 to  5 cloock' '8-5-2022, 6:00 PM' 'After 8'
 'ANY TIME AFTER 12PM' '10:30 AM' 'After 4pm' 'Afternoon (4 to 6)'
 '31-12-2023, 10:53 PM' 'Anytime ' 'Udydhdydydy' '9 Am -3 Pm'
 '03-11-2023, 9:28 AM' '10:00AM' 'بعد الظهر' 'After 6pm' 'any time ' '8.5'
 '25/12     3pm' '17-12-2023, 12:23 PM' '18-01-2024, 11:26 AM'
 '20-11-2023, 5:02 PM' '30-10-2023, 10:09 PM' '05-01-2024, 9:38 PM'
 '04-11-2023, 3:51 PM' '5-11-2022, 11:00 ص' '04-01-2024, 10:15 PM'
 'Monday 13/01/2020 @ 12:00 pm ' 'not after after 9 morning 19 :00 '
 '24-01-2024, 5:52 AM' '07-12-2023, 1:31 PM' '9-6-2023, 1:30 PM'
 'Everyday 8am-3pm' 'Saturdays' 'Tomorrow 7pm' '08-09-2023, 3:44 AM'
 'Any day, time between 11am and 9pm' '8pm' 'Random' '21-01-2024, 9:55 AM'
 '06-10-2023, 8:49 PM' '12-01-2024, 8:28 AM' '10:00 AM' '3pm'
 '02-01-2024, 4:49 AM' 'Please email' '21-10-2023, 2:00 PM' '8 pm to 10pm'
 '29-12-2023, 4:09 PM' '30-12-2023, 2:05 PM' 'Before 5 pm' '11 am- 1 pm'
 'After 2 pm' '28-5-2023, 1:30 م' "I'd Rather your guys emailed."
 'before iftar' '4-Mar' '3:30 afternoon ' 'before 5pm'
 '19-01-2024, 10:50 PM' '10:00 - 17:00' '25-3-2023, 10:30 AM'
 'from 12 noon to 5 pm' 'At 14:00 pm ' '5pm' '10' '1300'
 '06-01-2024, 1:25 AM' '04-09-2023, 11:40 PM' '03-11-2023, 12:37 AM'
 '07-01-2024, 5:31 PM' 'Any day from 3pm ' '9am-12am' 'anytime ' '3:30 PM'
 '29-11-2023, 7:37 PM' '08-09-2023, 12:27 AM' 'After 3 PM' '8pm '
 'after 5pm' 'after 3 pm ' '1pm-8pm' '1:00pm' 'مساء' 'From 4 to 10 PM'
 '10:00 PM' 'By mail better  because i work and finish later'
 '08-12-2023, 7:06 AM' 'ww' '06-11-2023, 7:45 PM' 'after 6'
 'Anytime today as I wanted to see a duplex apartment tomorrow please. Thx'
 '08-12-2023, 9:26 PM' '7:30 PM' 'Tomorrow at 8 PM' '25-10-2023, 9:13 PM'
 'today Tuesday at 5:00pm or tomorrow Wednesday at 11:00am KSA time.'
 'At 16:00' '10-02-2024, 3:34 PM' '50546490' '9pm'
 'Sunday and saturday from 10 Am to 8 Pm' 'Daylight ' '١٢٣ق٥'
 'After 5 pm weekend ' '24-11-2023, 3:35 AM' '18-12-2023, 1:48 AM'
 '19-11-2023, 5:00 PM' 'Between 6:7 pm' '07-01-2024, 2:37 AM' '2-4 pm'
 'عبر الايميل ' 'Now' 'Tomorrow after 4 pm'
 'asked to be contacted on evening' '31-May' 'Mornings'
 '20-11-2023, 5:48 PM' '06-12-2023, 2:26 PM' '8 p.m' 'Whatsapp please' '6'
 '11 am Saturday ' 'ant time' 'any' 'Yes' 'From 12 pm to 7 pm '
 '18-11-2023, 3:15 PM' 'any time,with whatsapp' '12-5-2023, 2:00 PM'
 'اي وقت' '29-4-2023, 9:00 PM' 'الساعه ٤ عصرا' '7-10 pm'
 '16-11-2023, 2:05 PM' 'noon' '10-02-2024, 12:02 PM' '11:30 AM' 'After 12'
 '3العصر' '3pm ' '4/2 at 3 pm' '23-11-2023, 3:14 PM'
 '23-10-2023, 12:57 AM' '5/12/2018.   4pm' '7:30 AM to 7:30PM USA time NY'
 '6 to9 pm' 'Today- Now' '05-12-2023, 10:30 PM' '16-09-2023, 10:42 PM'
 '15-7-2023, 1:00 PM' 'Morning' '11-11-2023, 5:26 PM' '5-8 pm'
 '1002139123' '5pm usa time' '06-10-2023, 2:44 PM' 'do not call'
 '29-08-2023, 7:02 PM' 'after 5 PM' '03:00PM' '2-3 pm'
 '26-01-2024, 8:11 AM' 'Anyday after 5 pm Cairo Time' 'قناة دشنا'
 '6 pm to 9 pm' '26-11-2022, ' 'Today' '17-12-2023, 3:46 AM'
 '12 pm. : 3  pm.' '29-11-2023, 1:24 AM' 'flexible' '1pm-6pm'
 '01-09-2023, 4:45 PM' '04-12-2023, 8:25 AM' 'بعد العصر '
 '05-12-2023, 3:14 PM' 'cfsx' '31-08-2023, 6:17 AM' '12pm -4pm '
 'Daytime any day' 'any ' 'AM' '8-10 am your time ' '18-8-2022, 11:30 AM'
 'after maghrib' 'asked to be contacted on 10a.m' '12pm' '4'
 '23-11-2023, 10:55 AM' 'Sunday 9:30am-10am EST' '28 March, 3 pm'
 '1285202030' 'After 3 pm' '18-7-2022, 1:00 م' '9-9pm' 'From 9 am to 5 pm'
 '18-12-2023, 5:39 AM' '11:30' '8:00 to 12:00 AM' 'after 14:00 PM'
 'from 7 PM' '3 p.m.' '10-02-2024, 10:03 PM' '03-11-2023, 3:54 PM'
 '15-7-2023, 3:00 م' '26-12-2023, 3:20 PM' '12pm  to 7pm' 'Wats'
 'After 5:00 pm' 'اى وقت' '5pm -8pm' '2pm' ' 7 am to 8 am central time'
 'afternoon time ' 'اي ةقت' 'after  noon' '1230:1430' '5'
 '07-01-2024, 11:04 PM' '07-10-2023, 11:04 PM' '18/09/2020-11:12'
 'من الثالثه بعد العصر' '23-11-2023, 11:47 AM' '06-11-2023, 9:00 PM' '11'
 '6-9-2022, 5:00 PM' 'mail please emadelrayes@hotmail.com'
 'From 12 to 10 ' '01-12-2023, 8:18 AM' 'Email' 'After 6 pm '
 '10-02-2024, 1:12 PM' 'Any day (11:00 am - 3:00 pm)' 'Ater1pm'
 '12:00 noon ' 'Saturday ' 'after 10 am' 'Late evening after working hrs'
 '12' '23-01-2024, 11:04 PM' 'After 12pm' '2 pm till 3 am' 'الواحده ظهرا '
 'after 12 PM' 'After 10 pm. o’clock' '10-02-2024, 4:33 AM'
 '01-01-2024, 12:05 AM' 'After 6 pm' 'العصر' 'From 2pm to 6pm'
 'Arter 2 pm' '10-12-2023, 8:07 AM' '8/3/2018' '17:00' '1100 am'
 '06-01-2024, 11:57 PM' 'after 5 pm' '10.00 pm' '08-12-2023, 4:43 PM'
 '09am : 6pm' 'before noon today if possible' 'Evening time'
 '29-12-2023, 8:18 PM' 'All the day' '07-09-2023, 7:43 PM'
 'Any Time after 8PM ' 'Sunday ,, 2 pm' '04-12-2023, 9:16 AM'
 '19-11-2023, 6:33 PM' 'evening 5pm' '03-02-2024, 6:57 PM'
 '12-8-2023, 9:00 PM' '07-12-2023, 3:56 PM' '17-10-2023, 4:44 PM'
 '1:00 _ 5:00' 'From 2pm to 6 pm' '29-11-2023, 10:38 PM'
 '10-02-2024, 2:17 PM' '05-11-2023, 7:27 PM' '24-08-2023, 5:50 PM'
 '11-12-2023, 3:33 PM' 'After 9:00 pm ' '15-01-2024, 1:17 PM' 'afternoon'
 '31-3-2022, 10:00 AM' '4 - 10 PM CLT' '04-01-2024, 10:07 PM' 'الآن'
 '11-12 am' '11am :1pm' '19-4-2023, 11:00 AM' '3-7-2023, 12:00 م'
 '15-5-2023, 5:00 PM' 'at 3 pm' '12-12-2023, 3:47 PM' '4pm'
 '\xa0contact on 3/7 after 12 pm' '11a.m' '04-01-2024, 3:25 AM'
 '26-10-2023, 12:05 AM' '01-11-2023, 11:29 PM' 'After 18:00pm'
 'Tomorrow pm' '٢ ال ٦' '09-09-2023, 5:11 PM' '12:00pm  to 10:00 pm'
 '24 November afternoon ' 'After 6:00 PM Cairo Time' 'Weakend '
 'afternoon/night' '3 to 6' '10am to 4 pm ' '20-11-2023, 9:27 AM'
 '0600 PM' '3' '25-12-2023, 12:30 AM' 'From 9: AM to 10:00 PM'
 '26-11-2023, 10:41 PM' 'After 4 pm' 'Anytime on WhatsApp '
 '20-11-2023, 12:34 PM' 'From 2 to 6' 'morning at 10'
 '31-10-2023, 4:37 PM' 'after 6 PM' 'Sometime' '7-Mar' 'Friday after 4 pm'
 'after 5:00 pm' 'Any ' 'Noon Time .' 'Happy ' 'shtr'
 '24-11-2023, 10:01 PM' '16-4-2022, 12:00 PM' 'day time'
 '22-11-2023, 6:20 AM' '30-09-2023, 1:39 AM' 'Night' '1-3pm ' '28-7 11a.m'
 '03-12-2023, 9:33 AM' '20-9-2022, ' 'After 8pm' 'After 1pm'
 '24-12-2023, 9:46 AM' '12 noon' '03-10-2023, 9:43 PM' 'From 6pm to 8pm'
 'Starting from july 01' '8-5-2023, 10:00 AM'
 'Every day after 6 pm expect friday' '7pm' '10 am  to    4 pm' '14'
 '20-11-2023, 6:14 PM' '17pm' '2-10 pm' '02-01-2024, 10:02 PM' '6p.m'
 '10:00 A.M' 'Tomorrow morning' '7-5-2022, 1:00 PM' 'مساء ' 'After 3PM'
 '10 am today' '12:00 م' '٤مساء' 'شقه دور مكرر ' '03-11-2023, 1:18 PM'
 'Su-Th/10-17' '03-11-2023, 1:05 AM' 'From 10 to 5 daily '
 'After 5:00 pm -' '25-6-2023, 10:00 AM' '09/09/2018. 14h' '15-11-2022, '
 '01-11-2023, 5:07 PM' 'بليل' '04-10-2023, 1:53 AM' '3:00pm to 9:00pm'
 'Any time before 8pm' 'اي وقت واتس ' 'Around 9pm ' 'Am'
 '08-11-2023, 9:38 PM' 'After 18.00' '22-12-2023, 10:50 PM'
 '26/1. From 10am.  to11am' '4_ 5 p.m & 2 _ 3 A.m' '6.00 pm' '٠'
 'Tomorrow ' '4/11/2018  any time ' '10.00 AM TO 12.00 AM'
 '21-09-2023, 3:03 PM' '10 AM to 4 PM' 'Before 3 PM - Preference morning '
 '9:00am - 9:00 pm' 'At any time(24 hours).' 'Before 3 pm' '22-8-2022, '
 '20-01-2024, 8:45 AM' '26-12-2023, 2:35 PM' '12-09-2023, 11:03 PM'
 ' 12 pm ' 'mornning time' '09-01-2024, 12:53 PM' '11-12-2023, 1:46 PM'
 '23-12-2023, 7:07 PM' '20-11-2023, 1:03 AM' '1500 UK time '
 'Whats app plz' '27-11-2023, 1:04 AM'
 'Any time during the day and not after 10 pm' 'After 6'
 'Today morning - 10 am' '4 to 6 pm' 'Morning 10 am' '28-1-2022, 3:30 PM'
 '19-6-2023, 12:30 PM' '26-11-2023, 9:02 PM' '26-01-2024, 12:50 PM'
 '8-8-2020. /2 pm o’clock ' '114111' '1-3 p.m.' '13-11-2023, 12:09 AM'
 '28-11-2023, 8:04 PM' '29-12-2023, 7:31 AM' '26-10-2023, 10:56 AM'
 'Anytime of the day' '06-12-2023, 12:20 AM' 'August 21st at 2 pm'
 '27-2-2023, 3:30 PM' 'after 6p.m' '23-12-2023, 5:34 PM'
 '02-02-2024, 10:30 AM' '03-11-2023, 11:12 AM' '09-01-2024, 6:40 PM'
 'after 3 pm' '25-3-2022, 3:00 PM' 'any time after 6 pm'
 '09-02-2024, 6:21 PM' '22-12-2023, 3:25 PM' '6 pm and afterwards'
 '24-9-2022, 5:30 PM' 'after 5 or during weekend - ' '20-3-2023, 7:00 م'
 'all day' '20-12-2023, 6:02 AM' 'Eny taim' '07-11-2023, 5:24 PM'
 'After 5' '9-Jul' '25-01-2024, 1:38 PM'
 'WhatsApp me the info please on the provided number'
 '26-6-2023, 11:30 AM' 'Tomorrow from 9: 3' 'email ' '5-8 PM'
 '27-12-2023, 1:39 AM' 'No9n' 'After 5 pm ' '23-3-2022, 6:30 PM' '6:30 PM'
 '22-7-2023, 11:30 AM' '11-11-2023, 1:02 AM' 'الان' '25-2-2023, 1:00 PM'
 'From 4PM until 9PM' '28-7-2023, 5:00 PM' '01-01-2024, 4:59 PM'
 '3-3-2023, 6:00 م' '10:30AM' '05-01-2024, 1:40 AM' '22-09-2023, 3:28 PM'
 'Any time by whatsapp' 'after 6:30 pm' '8:00 - 9:30 P.M'
 '16-10-2023, 9:19 PM' 'morning time' '07-01-2024, 12:21 AM'
 '08-11-2023, 1:58 PM' '04-01-2024, 12:06 PM' '19-09-2023, 10:09 PM'
 '9.30 am - 5.00 pm' 'After 5 PM' 'from 11 am up to 4 pm'
 '05-11-2023, 8:34 PM' '4PM' '10-11-2023, 7:20 PM' '8:00pm'
 '19-8-2023, 11:30 AM' '06-09-2023, 4:43 PM' '1-Oct' '9 مساءا'
 '03-02-2024, 4:51 AM' 'From after 1,' '08-12-2023, 12:33 PM'
 'at  8.00 pm.' '22/3الساعة 1 حتى 3' '14-11-2023, 8:12 PM'
 '8 am Houston time' 'After 15:00 ' 'الساعه 10ص' '05-09-2023, 9:17 AM'
 '18-11-2023, 11:21 AM' 'At night' 'Day' 'By WhatsApp anytime .'
 '13-8-2023, 1:30 PM' '1' 'after 5 pm ' 'after noon' '01-12-2023, 7:32 PM'
 'Week days from 11 AM to 5 PM' '08-02-2024, 11:01 AM' 'after ramadan'
 '11-09-2023, 6:34 AM' '25-01-2024, 1:48 PM'
 "Any afternoon or evening from 5pm or husband's telephone +201018338771 Ged"
 'Saturday. 2-5 pm' '16-11-2023, 11:38 AM' '11/8/2018' '1pm to 3pm'
 '25-12-2023, 11:02 AM' '5pm - 11pm' '12nigat' 'after 6 pm '
 '30-6-2023, 10:30 AM' '8 TO 10 am' '15-10-2023, 3:26 AM' '22.2' '11-Nov'
 '27-6-2023, 1:00 PM' 'before 4 or after 8 ' '11am  till 11 pm'
 '1 PM - 10 PM' '22-10-2023, 5:13 AM' 'after 8 pm ' '10:00 am to 7:00 pm'
 'Noon ' '18-09-2023, 1:11 AM' 'بعد العشاء عندنا' '04-11-2023, 10:49 PM'
 'Anytime during the morning' '11:00 PM' '11-09-2023, 7:13 PM'
 '24-08-2023, 9:35 AM' '29-08-2023, 1:59 PM' 'Saturday 13th October'
 '5:00' '09:00-23:00' 'Any day at 10 am, other than weekend '
 'After 5pm Cairo time' '5:30 PM' 'morning ' 'July 21 at 12 noon'
 'Any time just notify me through what’s app' '10-12 am ' '18-08-2019 '
 'any time before 7 pm' '10-01-2024, 1:41 PM' '8 - 12 PM'
 'Any time via whatsapp ' 'evening ' '20-11-2023, 12:54 AM' '15:30 pm'
 '01-11-2023, 12:51 PM' 'بعد الواحدة ظهرا' '20-3-2023, 11:00 AM' '12 30'
 'from 4pm to 8pm' '14-12-2023, 1:44 PM' 'Today after 6'
 '06-12-2023, 9:36 PM' '09-10-2023, 11:55 PM'
 'Starting 6.30 pm weekdays and any time in weekend' '16-11-2023, 9:31 PM'
 '12:08 PM' 'Tomorrow at 10 am' '٩pm' 'Anytime after 4pm Egypt Time '
 '10am' '1PM' '22-11-2023, 12:07 PM' 'من 9 ال 5 مساءا'
 '19-01-2024, 11:03 PM' '11/17/2018' 'after 7 pm' '5/8/2019    8 to 10PM'
 '5-7-2023, 6:00 PM' '02-09-2023, 3:04 PM' '01-01-2024, 10:36 PM'
 '26-7-2023, 12:00 م' '13:00 / 18:00' '12-11-2023, 8:08 AM'
 '16-01-2024, 6:16 PM' '19-12-2023, 11:09 PM'
 'Between 13:00hr and 21:00hr Egyptian time.' 'from 10 to17' 'Pls email'
 '31-01-2024, 6:39 PM' 'E-mail , WhatsApp' '10:30PM '
 '20-3-2022, 12:30 PM' 'after 1 pm' 'after 4:00 pm' '11-09-2023, 3:47 PM'
 '08-01-2024, 2:44 PM' '09-12-2023, 11:50 AM' '7 p.m' 'whatsapp'
 'From 1 pm till 6 pm' '08-12-2023, 10:18 PM' 'After 11 am' '27-07'
 'بنك مصر' '20-7-2023, 10:30 AM' '11 to 2' '27-08-2023, 3:46 AM'
 'Everyday from 4pm' 'Please call her now' 'Sept 2 , at 6:00 pm '
 'After 11 am ' 'Weekend' '4.35' '5 to 8 PM' 'Anytime after 14:00'
 '06-11-2023, 7:58 AM' '29-01-2024, 10:09 PM' '10.30 pm 17/3'
 'Sunday from 2pm till 8pm ' 'كل الاوقات ' '6 pm to 8 pm'
 '07-01-2024, 1:24 PM' '10-11-2023, 4:30 PM' 'After 5:00 PM' 'After 20'
 'Sunday  at 5:00 pm' 'أي وقت' '14-11-2023, 9:29 PM' '18-01-2024, 7:17 PM'
 'day time ' '5.00 pm' 'After noon' 'Sunday-Wednesday '
 '16/9/2018 ,all day' '20-11-2023, 6:06 PM' '16-11-2023, 1:25 AM'
 '13-12-2023, 8:37 PM' '10.00AM  -21PM' '12-09-2023, 3:24 PM'
 'After 5 P. M' 'Any time will be fine' '12-12-2023, 8:08 AM'
 '19-10-2023, 11:42 AM' 'After 7pm' '19-11-2023, 4:24 PM'
 '22-12-2023, 12:20 PM' 'free' 'After 8 pm ' 'From 4 pm.to 6pm' '1-5 pm'
 '04-11-2023, 1:07 PM' '30-4-2023, 5:00 PM' '11-7 pm' 'Gsga' 'after 3 p.m'
 '14-8-2022, 6:30 PM' '١' '10-10-2023, 12:55 AM' '10-12 am'
 '22-3-2023, 10:00 AM' '02-12-2023, 12:50 AM' '08-11-2023, 5:08 PM'
 'Anytime after 5pm and until 9:30 pm' '13-12-2023, 11:36 PM'
 '1 July 2019 , 1 pm' '28-12-2023, 11:21 AM' '11.03.2019'
 '08-12-2023, 11:33 PM' 'From 10 am to 10pm except from 2 pm to 6 pm'
 '11-09-2023, 4:19 AM' '19-11-2023, 6:21 PM' '2-Oct' '27-12-2023, 2:45 AM'
 'After 3 P.M starting from the 10th of March' '04-11-2023, 12:37 AM'
 '29-10-2023, 7:20 PM' '16:00-22:00' 'today' '26-5-2023, 11:30 ص'
 'Saturday after 2pm' 'Before 4 pm' '19-11-2023, 2:34 PM'
 '14-11-2023, 7:59 PM' '5:00pm' 'Anytime after 4 pm' 'Any Time'
 '22-12-2023, 6:22 AM' 'After 7 PM' '06-01-2024, 6:05 PM'
 '16-12-2023, 11:17 PM' '9 to 6' '21-01-2024, 1:56 PM'
 '01-01-2024, 5:01 PM' 'From 10:00 am to 5:00 pm' '04-09-2023, 2:10 AM'
 'All day ' '29-10-2023, 1:13 AM' '27-4-2023, 6:00 PM'
 '31-7-2021, 1:30 PM' 'monday' '25-12-2023, 3:32 PM' '4-5 pm'
 '31-8-2022, 3:00 PM' ' 3_8 pm' 'Tomorrow 5pm' 'From 1:pm- 4:pm'
 'asked to be contacted on In the morning after 10:00 am .' 'After 4 PM'
 '10Am-3Pm' 'any day in the morning 9-11am' '29-10-2023, 11:12 PM'
 '30-08-2023, 7:52 PM' '1.00pm' '10am to 6 pm ' '8 Am till 8 pm'
 'Please send me prices by mail' '11 Am-16 PM' 'on 8:00 pm'
 '10-09-2023, 2:34 PM' 'Today. 10 pm' '16-11-2023, 12:19 PM' '9:30 AM'
 'asked to be contacted on 3:30 ' '30-12-2023, 12:54 AM' '8-Apr'
 '22-11-2023, 3:35 PM' 'Friday ' '10-01-2024, 6:30 AM'
 '23-01-2024, 12:49 PM' 'In 2 years ' '8' '22-11-2023, 2:55 AM'
 '03-01-2024, 5:11 AM' '7' '13-11-2023, 6:19 AM' '09-09-2023, 9:29 PM'
 'In the morning after 12 ' '07-09-2023, 3:06 AM' '3/4/2019 11:00'
 '20-7-2023, 10:00 AM' '05.00 pm' '5-8-2023, 2:30 PM'
 '24-10-2023, 9:38 PM' '25-12-2023, 8:33 PM' '21-12-2023, 8:50 AM'
 '10:00am_10:00pm' '08-11-2023, 2:00 AM' 'Today '
 'from 3 to 6 pm kuwait timing' '18-11-2023, 9:29 PM'
 '30th of March after 12.30 pm USA time' '07-09-2023, 8:11 PM'
 'After 2 pm ' 'Any day after 10;00am' '9' '10pm' '25-01-2024, 10:57 PM'
 '11-01-2024, 8:21 AM' '10-6-2023, 10:00 AM' '18-09-2023, 5:20 PM'
 '12:30PM' 'After 11am' '28-08-2023, 1:42 PM' '06-11-2023, 11:12 AM'
 '08-02-2024, 5:40 PM' '23-Sep' '11.45' '18-12-2023, 12:05 AM'
 '08-10-2023, 8:29 PM' '30-09-2023, 2:21 PM' 'ASAP' '8-7-2023, 4:00 PM'
 '11am to 3pm' 'Easy' 'اي وقا' 'in the morning before 12' '28/8/2018 '
 'Anytime after 4 00 PM' '19-10-2023, 10:06 PM' "After 4 O'Clock PM"
 '25-7-2023, 11:30 ص' '22-12-2023, 7:13 PM' '18-11-2023, 2:43 PM'
 '29/12 @ 12 ' '08-01-2024, 7:59 PM' '6-3-2023, 6:00 PM' 'ANY TIME'
 '20-7-2023, 3:00 PM' '20 July 19 /4:00Pm' 'After 7' '21-01-2024, 1:33 AM'
 '11-01-2024, 7:51 AM' 'Now ' '17-4-2020 , 7Pm' '04-10-2023, 1:17 PM'
 'from 6 pm' '8 am to 4 pm ' '10-01-2024, 8:17 PM' '01-02-2024, 7:19 AM'
 'Day time' 'After 8 pm' 'After 6 pm Dubai time '
 '10/25/2018 @ 5pm Egypt time will be 11 am USA time' 'After 7:30 pm'
 'Whatsapp']
====================================
budget : [          nan 1.2000000e+06 2.0000000e+06 1.5000000e+06 1.4000000e+06
 1.2000000e+07 3.9000000e+06 4.0000000e+06 7.0000000e+06 3.0000000e+07
 5.0000000e+06 8.0000000e+06 2.5000000e+06 1.0000000e+06 3.5000000e+06
 2.4000000e+06 3.0000000e+06 6.5000000e+06 1.1000000e+07 6.0000000e+06
 2.8000000e+06 1.0000000e+07 3.3000000e+06 1.5000000e+07 9.0000000e+05
 7.5000000e+06 9.0000000e+06 1.6000000e+06 1.3000000e+07 2.3000000e+07
 4.5000000e+06 2.0000000e+00 2.3000000e+06 1.0000000e+00 3.2000000e+06
 2.0000000e+07 6.7000000e+06 1.0999999e+07 2.5000000e+04 5.0000000e+05
 2.2000000e+07 7.0000000e+05 9.3000000e+06 3.7000000e+06 8.0000000e+05
 5.5000000e+06 6.3000000e+05 1.1800000e+07 4.6000000e+05 3.8800000e+05
 6.1000000e+05 6.0000070e+06 7.8000000e+06 6.0000000e+05 3.0000000e+00
 2.5000000e+03 1.7000000e+06 1.4000000e+07 5.3000000e+06 1.5500000e+06
 2.7000000e+06 2.5000000e+07 1.0000000e+01 4.4170000e+06 4.6000000e+06
 5.6000000e+06 9.0000000e+00 5.9999970e+06 1.4042960e+06 5.8000000e+05
 6.6000000e+06 2.2000000e+06 3.1800000e+06 2.8000000e+07 4.3000000e+06
 5.0000000e+00 8.7600000e+05 2.8200000e+05 4.0000000e+00 1.8000000e+06
 1.3500000e+06 1.3000000e+06 9.6800000e+05 3.6000000e+06 1.6400000e+06]
====================================
created_at : ['9/7/2018 15:58' '5/4/2022 19:59' '3/22/2023 5:23' ... '2/4/2022 22:50'
 '1/22/2023 7:13' '12/4/2022 10:12']
====================================
updated_at : ['1/24/2024 15:07' '1/10/2024 13:10' '2/7/2024 15:45' ...
 '10/17/2023 13:45' '12/20/2023 13:41' '1/22/2023 9:29']
====================================
user_id : [2.942e+03 1.494e+03 4.043e+03 3.805e+03 4.003e+03 3.965e+03 4.084e+03
 1.589e+03 6.800e+01 2.682e+03 4.041e+03 5.090e+02 2.748e+03 1.820e+03
 4.680e+02 6.250e+02 3.997e+03 2.910e+02 4.072e+03 4.118e+03 3.909e+03
       nan 3.471e+03 1.954e+03 2.321e+03 4.800e+02 3.500e+02 3.900e+03
 2.685e+03 4.250e+02 3.975e+03 1.689e+03 7.350e+02 2.387e+03 4.067e+03
 3.894e+03 4.210e+02 2.440e+02 3.897e+03 6.000e+02 4.136e+03 3.460e+02
 3.994e+03 3.337e+03 3.000e+00 1.423e+03 1.500e+02 1.326e+03 3.941e+03
 2.514e+03 2.350e+02 3.802e+03 4.069e+03 3.406e+03 2.521e+03 4.068e+03

In [21]:
for column in sale.columns:
    print(f"{column} : {sale[column].unique()}")
    print("====================================")

id : [11218   776  3016 ...  3490  3670  3671]
====================================
lead_id : [130316  32565  20428 ...   1550 324105 360640]
====================================
unit_value : [17770000.   648000.  8912000. ...  2640000.  3824000.  1200000.]
====================================
unit_location : ['New Cairo' 'New Capital City' '6th October' 'Mostakbal City'
 '6th of October City' nan 'El Sheikh Zayed' 'North Coast' 'Ain Sokhna'
 'Cairo' 'Sila' 'El Shorouk' 'New Heliopolis' 'Somabay' 'El Gouna' 'Jayd'
 'The Axis' 'Jefaira - The Furl' 'Bay 7' 'Caesar Bay' 'Hurghada' 'Zed '
 'SILA' 'Joulz' 'Madinaty' 'Haptown' 'Port Said' 'Ras Sudr'
 'Orascom - Owest' 'Maadi' 'Baymount' 'Kattameya Creeks' 'O West']
====================================
expected_value : [          nan 1.0000000e+07 1.1000000e+07 4.0000000e+06 9.7560000e+06
 5.5000000e+06 3.0000000e+06 9.0000000e+06 5.0000000e+07 5.0000000e+06
 4.0000000e+00 4.5000000e+06 1.6000000e+07 6.0500000e+06 2.0000000e+07
 1.2000000e+07 5.7000000e+06 2.3467390e+06 6.0000000e+06 1.8000000e+07
 3.5000000e+06 5.8818600e+06 4.9000000e+06 1.5000000e+07 1.4000000e+07
 3.0000000e+07 8.0000000e+06 8.9000000e+06 7.5000000e+06 1.1510000e+07
 3.6000000e+07 1.0300000e+07 2.8000000e+07 6.9000000e+06 1.0000000e+01
 7.0000000e+06 2.5000000e+07 3.2000000e+07 1.0000000e+00 2.5000000e+06
 4.6320000e+06 2.0000000e+06 6.1980000e+06 2.6000000e+06 2.4000000e+06
 3.1800000e+06 4.2000000e+06 3.2000000e+06 2.2800000e+06 5.1000000e+06
 5.2000000e+06 4.4000000e+06 1.2220000e+07 7.3331100e+06 3.2768000e+06
 4.3000000e+06 3.8000000e+06 1.8500000e+07 8.5000000e+06 4.0000000e+07
 5.8000000e+06 2.0000000e+00 8.0000000e+00 1.9821837e+07 7.9371110e+06
 9.9000000e+06 6.1000000e+06 6.5000000e+06 1.0244947e+07 4.7000000e+06
 2.4000000e+07 1.2283917e+07 4.6943000e+06 4.1500000e+06 3.5530000e+06
 1.7000000e+06 6.0000000e+07 3.0932000e+06 9.4558840e+06 8.2000000e+06
 6.0000000e+00 5.0000000e+00 3.3000000e+06 2.2000000e+07 1.3000000e+07
 1.0500000e+07 1.1500000e+07 3.2140000e+06 6.8000000e+06 7.1340000e+06
 6.4000000e+06 6.2000000e+06 5.9209430e+06 1.1499643e+07 2.6000000e+07
 2.8340000e+06 1.1110000e+06 6.1940000e+06 3.7000000e+06 2.5700000e+06
 6.5000090e+06 5.0000000e+05 3.2710000e+06 6.3000000e+06 9.5000000e+06
 8.7330000e+06 2.9000000e+06 2.6580000e+06 2.8800000e+06 2.9283980e+06
 3.9771000e+07 3.7640000e+07 1.2494720e+07 2.7310000e+06 4.2160000e+06
 2.7900000e+06 1.3303000e+07 3.3650000e+06 2.2000000e+06 1.3500000e+07
 3.4130000e+06 4.1100000e+06 6.4800000e+06 5.6290000e+06 1.9600000e+07
 6.0712270e+06 4.8000000e+07 3.6400000e+06 1.4526000e+07 1.3300000e+07
 1.7682000e+07 3.4112000e+06 6.0960000e+06 1.1052000e+07 7.2000000e+06
 3.2620800e+06 1.2700000e+07 2.3140000e+06 3.2310000e+06 3.3700000e+06
 6.7000000e+06 2.9230000e+06 2.2500000e+05 4.7962240e+06 3.4000000e+06
 6.8500000e+06 8.7000000e+06 6.6500000e+06 6.3868090e+06 3.6000000e+06
 3.0000000e+00 3.2550000e+06 3.3553700e+06 3.3234410e+06 2.1508100e+06
 3.2970000e+06 4.6000000e+06 2.8000000e+06 2.5800000e+06 1.6000000e+06
 2.9216600e+06 9.7000000e+06 2.5070000e+06 1.3800000e+07 3.1200000e+06
 1.9200000e+06 1.7160000e+06 4.4267000e+06 5.1212110e+06 7.6000000e+06
 3.8400000e+06 1.7000000e+07 3.1900000e+06 3.3000000e+07 2.3000000e+07
 4.8600000e+06 3.3010000e+06 2.6275290e+06 3.5542500e+06 2.8040000e+06
 3.9380000e+06 3.9551310e+06 5.1720000e+06 3.1000000e+06 1.0000000e+06
 5.3000000e+06 4.6540000e+06 7.8940000e+06 2.9324680e+06 9.9056870e+06
 8.3740000e+06 5.2500000e+06 5.1400000e+06 3.8040000e+06 3.8620000e+06
 3.7900960e+06 6.8000000e+07 1.3135650e+07 2.0030000e+06 3.0590000e+06
 4.3385780e+06 2.7052100e+06 6.2500000e+06 6.3010000e+06 4.8980000e+06
 1.0800000e+07 1.6988000e+06 3.7373000e+06 1.1850000e+06 2.0260000e+06
 2.3000000e+06 7.2900000e+06 3.9500000e+06 3.1466300e+06 3.9100000e+06
 8.8000000e+06 9.7336670e+06 3.6685450e+06 1.5000000e+06 6.5031750e+06
 2.6887920e+06 3.3461550e+06 5.1140000e+06 1.2460000e+06 2.9827670e+06
 2.0240000e+06 7.4170000e+06 4.9260000e+06 3.7230000e+06 4.6460000e+06
 1.4950000e+07 5.9447910e+06 4.5421250e+06 4.8630000e+06 1.5500000e+07
 1.1000000e+06 3.1552060e+06 6.8634500e+05 3.8120000e+06 2.6325300e+06
 5.1920000e+06 2.7000000e+06 5.0310000e+06 3.8777460e+06 5.1280000e+06
 6.2270000e+06 5.6000000e+06 4.9230000e+06 2.1000000e+06 2.8170000e+06
 4.4600000e+06 1.9571760e+06 3.2840000e+06 3.4950000e+06 5.6250000e+06
 6.5509360e+06 6.6000000e+06 6.9300000e+06 1.9487520e+06 2.6603640e+06
 4.3010000e+06 3.1650000e+06 4.7420820e+06 2.6201400e+06 8.6500000e+06
 2.0800000e+06 2.0320000e+07 7.4262440e+06 3.3563840e+06 6.3979250e+06
 9.3000000e+06 7.3000000e+06 1.9498120e+06 4.0434050e+06 3.0440900e+06
 4.1000000e+06 3.2820000e+06 2.8610000e+06 2.0640000e+06 1.0620000e+07
 4.6400000e+06 4.4150000e+06 2.3597730e+06 6.8446720e+06 1.3000000e+06
 2.8500000e+06 4.1263870e+06 7.3720000e+06 2.8751030e+06 6.3540000e+06
 5.3210000e+06 4.2500000e+06 3.8296800e+06 1.6500000e+06 2.7020000e+06
 5.7600000e+06 5.5320000e+06 5.3920000e+06 2.9880000e+06 1.5450000e+06
 4.4500000e+06 1.4000000e+06 6.0400000e+06 1.6630000e+06 2.7474130e+06
 3.4150000e+06 1.5194610e+07 9.8000000e+06 1.0450000e+07 1.4700000e+07
 7.7590240e+06 3.3100000e+06 1.1310000e+07 9.8143450e+06 1.0393000e+07
 4.8340000e+06 1.7400000e+07 1.0825000e+07 8.6000000e+06 8.9837000e+06
 2.2450000e+06 4.7500000e+06 1.6192000e+07 3.8170000e+06 1.0815370e+06
 1.4790000e+06 4.2730000e+06 2.0300000e+06 3.5550000e+06 5.9000000e+06
 4.8751060e+06 1.0439420e+06 9.3370000e+06 7.2164290e+06 2.4650000e+06
 5.8358750e+06 2.4320000e+06 1.3440000e+07 1.2900000e+06 1.1100000e+07
 1.6087815e+07 3.5000000e+07 1.9000000e+07 4.8610000e+06 1.0295046e+07
 1.1999972e+07 7.8565500e+06 9.9387210e+06 2.6400000e+06 3.8420000e+06]
====================================
actual_value : [17777000.       nan  8912000.  3658000. 13133000. 15227000.  6407000.
 10530000.  6892750.  6180000.  6198080.  4800000.  5030000.  5738077.
  8749914.  4635734. 10926000. 18833248. 19530000.  3075616. 21119000.
  3349540.  7320883. 13508000.  7886000.  4918968.  3374000. 19198000.
 19975000. 21942000. 19477560. 30957000.  4148147.  5908900. 38311000.
  4286705. 11450000.  2976000. 21508515.  9548000.  5507055.  6472000.
  8531000.  3113000. 16210000.  4771056.  9137000.  1600000.  6828000.
 14210141.  5018000.  4632000.  6435896. 14010000.  5294245.  2491000.
  6746912.  5370000.  3899678. 11340000.  6022000.  7264455. 15628000.
  7333110.  3276800.  3210115.  3580427.  3378000. 13489160.  7781000.
  6000000. 34351000. 13998735.  7260928.  4417000.  2099000.  3815899.
  7964000. 10997800. 18500000.  7725059. 18236000.  8000000.  3951000.
  4678000.  7340000.  3318478.  5379672.  9674644.  3136425. 13983962.
 17876804.  5297413.  6246000.  7792255.  3536148.  7150000.  6804280.
  5733975.  6480000.  7920000.  5287200.  4970000.  5842424.  4951128.
  6847904. 11640000.  3553000.  2560972. 27875700. 11275245.  2507582.
 11904000.  6442000. 17046770. 12922000. 17394000.  3792000.  3240000.
  4154159.  4043381.  5936195. 15000000.  3971714.  7810000.  5654371.
 25676000. 13443000. 20964312.  8487531.  4411000.  4833998.  6841000.
  6075990.  6674000.  2108306. 14407000.  7134000.  2468095. 11148459.
  3834000. 36649700.  8485331.  8502000.  3787000.  2879445.  8465000.
  6500000.  3480000.  8346715.  5920943. 17956400.  8371000.  4230000.
  7167000.  7110000.  1111000.  6835000.  5741000.  4303000.  7569037.
  5017391.  4311143.  3700000.  7831000. 12100000. 67800000.  1934200.
  7700000.  4373000.  6485000.  4500424.  5988622. 10065000.  3062500.
 11000000.  2415184.  7962604.  2692500. 13024901.  2236000.  6130763.
 11872729.  4750000.  5816106. 21415000. 11489059.  3829000.  3403800.
  8733000.  4150000.  3430000.  2175000.  3504000.  7480000.  3584000.
  2200000.  2940000.  4394000.  2509000.  4284000.  2270000.  3798250.
 16295100.  7559000.  2989000.  6850000.  3766000.  5711000.  3952300.
  8087000. 10612000.  2435950.  3015600.  4216000. 15491383.  7157422.
  2790000. 13799028.  4542125.  4622000.  5992058.  5040000.  4454354.
  5798168.  5200000.  5000000.  4118045.  9800000.  3659000.  4592000.
  7311619.  3897000.  5083000.  4240000.  6549288.  6865279.  5978883.
  3259000.  2075000.  3646800.  5411556.  3413000.  4218000.  4275000.
 19819443.  9460000.  2893000.  3360000.  5566000.  7800000.  6712035.
 11739363.  4521000.  3250000.  6465562.  3640000.  4472893.  4010000.
  5570000. 14527000.  5030025.  5100000.  8507250. 16000000. 10365000.
  6597006. 14670000.  1747000.  8792200.  3840900.  6441000.  3621000.
  3508000.  3952000. 33797000. 21409477.  5527206.  4080000. 10010000.
  4070000. 17683000.  3411000. 13180000.  2732000.  6157000.  5798519.
  4837004. 11052002. 10643000.  7300000.  2742230.  2283244.  7214762.
  5087616.  3105000. 12459000.  3190000.  5176000.  2168574. 17687000.
  3623000.  3231000. 13964000.  5130417.  4985200.  5869309.  4008000.
 14170379.  3370000.  6216210.  3220000.  3793196.  6306018.  4195000.
  2923000.  3560869. 11526000.  6473000.  2618000. 13735000.  3770000.
  1470528.  9751227.  5311289.   225000.  4806000.  1127000.  3877000.
  3590000.  3919000.  4460831.  5162000.  3851000.  3100000.  4605000.
  5177931.  8007300.  1727000.  5906959.  7198286.  4851840. 13737570.
 44420000. 11177400. 10580000. 10833000.  4335800. 13500000.  3972000.
  7880168.  3720000. 15863000.  7506712.  6239856.  3960000.  1850000.
  6255000.  6411664.  8574400.  3769682.  2652000.  5214000.  8060000.
 14589000.  3323441.  3355370. 14907703.  2695264.  4400000.  2150810.
 11302677.  3616359. 25512000.  3261759.  2312290.  3856000. 45231253.
  2921660.  7076000. 14789000.  3335160. 17625000.  3460000.  5805000.
 48957500.  4174000.  5589530.  2665543. 10462000.  4380000.  5593929.
 13828000. 13645000.  5967692.  5870401.  3840000.  6341437. 16090000.
 36734777. 13997242.  3104000.  6100205.  8921479.  2076200.  6523000.
  2945000.  2982726.  5372185.  3903000.  1829713.  7857300.  2528000.
 12098583.  1873013.  3140000.  5558255.  4860000.  2730000.  8364712.
  3449703.  3432000.  4457304.  3301012.  4517263.  2322000.  3486924.
  4477770.  4637000.  2735000.  3457414.  3436000.  9820000.  4126398.
  3938000.  3955131.  3490000.  3081830.  6442609.  5167866.  8206000.
  5670450.  6110000. 11349000.  6277776.  9305366.  4277470.  2627529.
  2355000. 15457747.  2167000.  3351250.  5171040.  3313000.  7318500.
 10980000.  8207000.  3764000.  1815685. 11861356.  2792000.  3556514.
  2192193. 17891000.  4220000.  2205000.  3010742.  7290000.  1826000.
  4273662.  6630529.  3731240.  3708637.  7360000.  5600000.  3425624.
  3253110.  6510000.  5144000.  3723000.  8468000. 12804677.  4613000.
  4691640.  1515472.  2730417.  6989000. 13040000. 15372000.  3314917.
  5450000.  3155206.  2938683.  2632530.  4926976.  8660000.  5149000.
  5075925.  6227000.  4107000.  1957176. 41392100. 10400000. 11960000.
 21700000. 10700000.  5950000.  3817211. 15666000. 29753219.  3008000.
  8242000.  8683000.  5710000.  6930000. 14225013.  5146000.  4161320.
 10120000.  4301000. 14702600.  1077000.  3994350. 10386000.  8821000.
 13404600. 11933000.  9113000.  4742082.  9029586. 10741000. 17337364.
  8650223. 11379550. 10793200.  3763124.  3887423.  3531102.  2164440.
 13102742.  8763700. 16325246.  5409000.  4817792. 13514000.  4654000.
  2931000.  5822800.  3252747.  5726000.  2676000.  3979540.  3408445.
  6438000.  6249866.  3019439.  5161000.  3622500.  5856000.  1949812.
  4043405.  3044091.  4642347.  4300000.  3282000. 13437000.  9857000.
  2861000. 23849000.  9260227.  3290000.  6977623.  4812000.  6149000.
  2545308.  6844672.  5529020.  5843000.  2178000.  5576000.  4685413.
  6011000.  2820860.  3398060.  6694534.  7180800. 10006066.  5630000.
  2875103.  3500000.  3990000.  2540000.  3551000.  5321000.  4250000.
  6418000. 12112000.  7960000. 11290000.  4426000.  3780000.  8269000.
 15245000.  4165700.  4146000.  3120000.  2717271. 23287241.  4032590.
  1643326.  4119767.  4240290. 10937000.  2727000.  3260000.  6138090.
  5572000.  3754354.  5532000.  3629838.  1847000.  1794500.  1805090.
  8467200.  4884000.  6388760.  5263920.  8446000.  8440000.  2828000.
  8090000.  6963571.  7280000.  6760000.  6849025. 11253650. 67200000.
  2978910.  2767930.  1401000. 18610000.  3423000.  7358738.  7460000.
 19884370.  3480189. 11664000.  6620000.  4040000.  6425000. 11376000.
 10810802.  3672000. 10082476. 14025017. 17000000.  2747413.  3152264.
  8637000.  6032000.  4076853. 12700000. 12696000.  9616189. 16380000.
  9744000. 15070000. 15194000.  9842000. 11764000. 10450000. 11875010.
 14798000.  7684000.  7759024. 10950000.  7170000. 14943000.  7602379.
 19272000.  8368000.  5879000.  7953000.  5612000.  8012600.  5315000.
 37021752. 13661172.  8128242.  3760000. 16203000.  8860000. 14631000.
 20585800.  5947602.  9814345.  5866119.  9170000.  8038000. 65197640.
  6060000.  5959000. 17446013. 17047858. 10825000. 19920000. 13300000.
 30889410.  4373186.  4143400.  6001345.  5868434.  5303000.  5858000.
  6010000.  7676000.  5517000.  4088213. 12600000.  7486710.  4794540.
  5870000. 20534754. 12994167. 25213000.  9867600. 36553000.  4720000.
  3448160. 23470000.  8616770.  5487000.  8983700.  8482000.  2245000.
  5222000.  1920000.  5172000.  2637650. 16020014.  3817000.  7440000.
  2870000.  5636232.  5859286.  3620000.  3900000.  3571000.  3555000.
  5090000.  3467000.  8800000.  5400000.  7900000. 11487000. 20717750.
 22656058. 10653000. 12486500.  5472765.  5980000.  4680000. 14586775.
  6160000.  9600000.  5745179.  4875106.  7610350.  1043942.  9492775.
  4241160.  2465100.  5835875.  3665700.  4946147.  2800000.  1243000.
  6694173.  2432000. 26935700.  9292506.  6079669. 11156709. 11648107.
 11602844. 10200000. 12444086. 20917000. 65216250. 16604874.  8064937.
 12053245. 12836000. 16087815. 45060000. 10718240. 12582929. 14409570.
 12292944.  3824000.  1200000.]
====================================
date_of_reservation : ['1/10/2024 0:00' '4/11/2021 0:00' '9/4/2022 0:00' '10/12/2023 0:00' nan
 '11/19/2023 0:00' '1/28/2024 0:00' '11/27/2023 0:00' '8/10/2023 0:00'
 '5/20/2023 0:00' '1/13/2024 0:00' '12/21/2023 0:00' '12/19/2023 0:00'
 '11/6/2023 0:00' '12/14/2023 0:00' '12/12/2021 0:00' '8/14/2018 0:00'
 '1/16/2024 0:00' '12/25/2022 0:00' '10/29/2023 0:00' '2/12/2022 0:00'
 '1/22/2024 0:00' '1/30/2024 0:00' '11/16/2023 0:00' '1/17/2024 0:00'
 '6/23/2022 0:00' '8/1/2023 0:00' '4/28/2020 0:00' '5/29/2023 0:00'
 '10/17/2023 0:00' '12/15/2019 0:00' '1/8/2024 0:00' '9/4/2023 0:00'
 '11/15/2023 0:00' '7/30/2022 0:00' '2/20/2023 0:00' '8/11/2022 0:00'
 '10/30/2023 0:00' '7/4/2023 0:00' '1/20/2024 0:00' '3/4/2021 0:00'
 '2/5/2019 0:00' '8/25/2022 0:00' '1/10/2021 0:00' '1/23/2024 0:00'
 '1/25/2024 0:00' '9/2/2021 0:00' '4/18/2023 0:00' '1/20/2022 0:00'
 '9/24/2023 0:00' '1/24/2024 0:00' '1/21/2024 0:00' '9/19/2022 0:00'
 '8/4/2021 0:00' '7/27/2023 0:00' '12/29/2022 0:00' '7/13/2023 0:00'
 '4/14/2022 0:00' '10/27/2022 0:00' '1/25/2023 0:00' '12/20/2023 0:00'
 '4/28/2022 0:00' '8/29/2023 0:00' '8/30/2023 0:00' '12/18/2023 0:00'
 '11/22/2022 0:00' '2/15/2023 0:00' '12/3/2023 0:00' '10/23/2023 0:00'
 '6/12/2023 0:00' '6/15/2021 0:00' '10/7/2023 0:00' '10/1/2023 0:00'
 '10/15/2023 0:00' '9/11/2023 0:00' '2/4/2024 0:00' '10/28/2020 0:00'
 '11/7/2023 0:00' '8/3/2022 0:00' '11/10/2022 0:00' '7/30/2023 0:00'
 '12/8/2022 0:00' '3/23/2022 0:00' '9/18/2023 0:00' '9/19/2023 0:00'
 '9/3/2023 0:00' '6/6/2022 0:00' '8/4/2022 0:00' '2/25/2023 0:00'
 '10/3/2022 0:00' '8/3/2021 0:00' '11/2/2022 0:00' '7/10/2023 0:00'
 '6/28/2021 0:00' '12/31/2023 0:00' '10/26/2023 0:00' '1/2/2024 0:00'
 '1/4/2023 0:00' '9/22/2022 0:00' '5/30/2023 0:00' '8/21/2023 0:00'
 '6/28/2022 0:00' '10/28/2023 0:00' '1/29/2023 0:00' '12/5/2023 0:00'
 '2/7/2024 0:00' '8/8/2023 0:00' '1/9/2024 0:00' '9/9/2023 0:00'
 '9/2/2023 0:00' '11/28/2023 0:00' '9/27/2023 0:00' '9/17/2023 0:00'
 '11/17/2021 0:00' '6/25/2023 0:00' '12/13/2023 0:00' '12/11/2023 0:00'
 '11/23/2023 0:00' '11/20/2023 0:00' '12/26/2023 0:00' '2/1/2024 0:00'
 '12/24/2023 0:00' '5/31/2022 0:00' '9/14/2023 0:00' '1/11/2024 0:00'
 '4/27/2022 0:00' '11/2/2023 0:00' '11/30/2023 0:00' '8/27/2023 0:00'
 '5/24/2023 0:00' '4/27/2020 0:00' '7/6/2020 0:00' '11/21/2023 0:00'
 '7/31/2023 0:00' '1/11/2023 0:00' '1/17/2023 0:00' '6/21/2023 0:00'
 '11/9/2023 0:00' '10/25/2023 0:00' '11/22/2023 0:00' '3/5/2023 0:00'
 '1/27/2024 0:00' '5/22/2022 0:00' '10/31/2023 0:00' '10/4/2023 0:00'
 '9/20/2023 0:00' '1/5/2024 0:00' '10/8/2023 0:00' '1/14/2024 0:00'
 '7/5/2022 0:00' '12/27/2023 0:00' '3/22/2023 0:00' '2/21/2023 0:00'
 '2/23/2017 0:00' '6/7/2023 0:00' '8/20/2023 0:00' '3/13/2023 0:00'
 '9/25/2023 0:00' '12/28/2023 0:00' '5/25/2022 0:00' '8/17/2022 0:00'
 '2/5/2024 0:00' '12/6/2023 0:00' '5/28/2023 0:00' '5/23/2022 0:00'
 '4/13/2022 0:00' '5/14/2022 0:00' '8/30/2022 0:00' '8/9/2023 0:00'
 '5/21/2022 0:00' '8/13/2023 0:00' '11/7/2021 0:00' '6/22/2023 0:00'
 '3/13/2022 0:00' '3/24/2022 0:00' '7/17/2023 0:00' '5/27/2021 0:00'
 '7/17/2021 0:00' '11/10/2023 0:00' '6/14/2022 0:00' '6/10/2023 0:00'
 '4/12/2023 0:00' '9/6/2021 0:00' '8/2/2022 0:00' '2/7/2022 0:00'
 '8/2/2021 0:00' '8/6/2021 0:00' '12/12/2023 0:00' '2/1/2023 0:00'
 '7/28/2022 0:00' '7/29/2023 0:00' '5/6/2022 0:00' '9/26/2022 0:00'
 '9/27/2022 0:00' '7/24/2023 0:00' '7/25/2023 0:00' '2/6/2024 0:00'
 '8/24/2022 0:00' '8/2/2023 0:00' '6/11/2020 0:00' '9/7/2023 0:00'
 '8/9/2022 0:00' '9/18/2022 0:00' '9/1/2022 0:00' '9/8/2022 0:00'
 '11/13/2023 0:00' '9/12/2022 0:00' '2/22/2022 0:00' '9/20/2022 0:00'
 '10/9/2023 0:00' '11/14/2021 0:00' '5/24/2022 0:00' '9/24/2022 0:00'
 '8/7/2022 0:00' '7/17/2022 0:00' '9/29/2022 0:00' '10/4/2022 0:00'
 '10/9/2022 0:00' '9/28/2022 0:00' '5/9/2023 0:00' '11/6/2022 0:00'
 '11/3/2022 0:00' '8/12/2018 0:00' '11/8/2022 0:00' '10/10/2023 0:00'
 '8/7/2023 0:00' '6/9/2020 0:00' '8/31/2023 0:00' '11/3/2020 0:00'
 '5/31/2023 0:00' '8/24/2020 0:00' '12/7/2022 0:00' '12/15/2022 0:00'
 '12/14/2022 0:00' '3/14/2023 0:00' '1/5/2023 0:00' '4/24/2021 0:00'
 '3/16/2023 0:00' '3/17/2023 0:00' '11/24/2023 0:00' '5/2/2023 0:00'
 '5/17/2023 0:00' '2/18/2023 0:00' '8/22/2023 0:00' '7/26/2023 0:00'
 '3/8/2023 0:00' '11/4/2023 0:00' '5/14/2023 0:00' '11/4/2020 0:00'
 '5/8/2023 0:00' '8/23/2023 0:00' '6/4/2023 0:00' '10/6/2023 0:00'
 '10/2/2023 21:00' '10/26/2022 0:00' '6/12/2022 0:00' '12/25/2023 0:00'
 '4/16/2023 0:00' '4/6/2023 0:00' '2/14/2023 0:00' '4/5/2023 0:00'
 '12/22/2022 0:00' '6/20/2023 0:00' '11/1/2023 0:00' '8/17/2023 0:00'
 '10/13/2022 0:00' '1/3/2023 0:00' '6/7/2022 0:00' '11/29/2023 0:00'
 '2/14/2019 0:00' '3/8/2022 0:00' '8/28/2023 0:00' '4/15/2021 0:00'
 '9/14/2021 0:00' '7/30/2021 0:00' '2/12/2023 0:00' '1/16/2023 0:00'
 '3/28/2018 0:00' '9/5/2021 0:00' '12/4/2023 0:00' '5/7/2023 0:00'
 '3/12/2023 0:00' '9/28/2021 0:00' '9/16/2021 0:00' '7/24/2021 0:00'
 '8/31/2023 21:00' '10/3/2021 0:00' '11/17/2022 0:00' '1/25/2022 0:00'
 '7/20/2023 0:00' '4/3/2022 0:00' '11/2/2021 0:00' '1/22/2023 0:00'
 '5/18/2023 0:00' '1/12/2023 0:00' '1/31/2023 0:00' '6/8/2023 0:00'
 '2/2/2023 0:00' '3/7/2022 0:00' '9/12/2023 0:00' '8/9/2021 0:00'
 '3/15/2023 0:00' '2/26/2023 0:00' '5/10/2023 0:00' '6/11/2023 0:00'
 '4/2/2023 0:00' '2/7/2023 0:00' '6/3/2023 0:00' '4/26/2023 0:00'
 '6/14/2023 0:00' '3/27/2023 0:00' '12/9/2023 0:00' '6/1/2020 0:00'
 '9/30/2019 0:00' '1/1/2023 0:00' '12/17/2022 0:00' '11/9/2022 0:00'
 '10/22/2023 0:00' '2/5/2023 0:00' '10/20/2022 0:00' '3/28/2023 0:00'
 '5/22/2023 0:00' '4/13/2023 0:00' '8/26/2023 0:00' '12/10/2023 0:00'
 '11/12/2023 0:00' '11/8/2023 0:00' '9/23/2023 0:00' '8/16/2023 0:00'
 '10/5/2023 0:00' '10/14/2023 0:00' '11/7/2022 0:00' '3/9/2023 0:00'
 '5/4/2023 0:00' '1/28/2023 0:00' '5/23/2019 0:00' '3/22/2022 0:00'
 '9/16/2020 0:00' '5/25/2023 0:00' '3/31/2022 0:00' '9/6/2022 0:00'
 '8/7/2021 0:00' '1/19/2023 0:00' '4/9/2022 0:00' '6/19/2022 0:00'
 '8/24/2021 0:00' '7/28/2021 0:00' '7/24/2022 0:00' '6/29/2022 0:00'

In [22]:
for column in property_type.columns:
    print(f"{column} : {property_type[column].unique()}")
    print("====================================")

id : [10. 13. 20. 21. 11.  5. 12.  8.  4.  9.  7.  6.  1.  3. nan]
====================================
property_type : ['Retail' 'Clinic' 'Serviced Apartment' 'Apartment' 'Cabin' 'Chalet'
 'Family House' 'Office' 'Penthouse' 'Studio' 'Townhouse' 'Twinhouse'
 'Villa' 'Duplex' nan]
====================================

In [23]:
for column in lead_type.columns:
    print(f"{column} : {lead_type[column].unique()}")
    print("====================================")

id : [  1.   3.   4.   2.  67.  68.  69. 100. 134. 133.  nan]
====================================
lead_type : ['Primary' 'Resale Buyer' 'Company Now' 'Seller' 'Brokerage' 'Freelancer'
 'Ambassador' 'Commercial Buyer' 'Commercial Rental' 'Commercial Seller'
 nan]
====================================

In [24]:
#change columns which datatype object  to datetime (needed ones only)
def cast_to_datetime(df, columns):
    for column in columns:
        df[column] = pd.to_datetime(df[column])
    return df

columns_to_cast_lead = ['date_of_last_request', 'created_at','updated_at','date_of_last_contact']  # List of columns to be casted in df1
columns_to_cast_sale= ['date_of_reservation', 'reservation_update_date','date_of_contraction']  # List of columns to be casted in df2

lead = cast_to_datetime(lead, columns_to_cast_lead)
sale = cast_to_datetime(sale, columns_to_cast_sale)

In [25]:

id_pk_lead = lead[lead.duplicated('id')]

In [26]:
#then id is pk
lead['id'].isnull().sum()

0

In [27]:
#checking for sale table
id_pk_sale = sale[sale.duplicated('id')]
sale['id'].isnull().sum()

0

In [28]:
#checking for property_type table
id_pk_property_type = property_type[property_type.duplicated('id')]
property_type['id'].isnull().sum()

1

In [29]:
property_type=property_type.dropna()

In [30]:
lead_type=lead_type.dropna()

In [31]:
lead['merged'].isnull().sum()

44945

In [32]:

def cast_to_nullable_int(df, columns):
    for column in columns:
        df[column] = pd.to_numeric(df[column], errors='coerce').astype('Int64')
    return df

# Example usage:
# Assuming lead is your DataFrame and columns_to_cast_lead is a list of column names
columns_to_cast_lead = ['user_id', 'area_id','compound_id','developer_id','meeting_flag']
columns_to_cast_sale=['property_type_id','area_id','compound_id']

lead = cast_to_nullable_int(lead, columns_to_cast_lead)
sale= cast_to_nullable_int(sale,columns_to_cast_sale)

In [33]:
property_type['id']=property_type['id'].astype('Int64')
lead_type['id']=lead_type['id'].astype('Int64')

In [34]:
property_type.dropna()

    id       property_type
0   10              Retail
1   13              Clinic
2   20  Serviced Apartment
3   21           Apartment
4   11               Cabin
5    5              Chalet
6   12        Family House
7    8              Office
8    4           Penthouse
9    9              Studio
10   7           Townhouse
11   6           Twinhouse
12   1               Villa
13   3              Duplex

In [35]:
property_type.isnull()

       id  property_type
0   False          False
1   False          False
2   False          False
3   False          False
4   False          False
5   False          False
6   False          False
7   False          False
8   False          False
9   False          False
10  False          False
11  False          False
12  False          False
13  False          False

In [36]:
#lead.to_csv('data/leadpy.csv', index=False)
#sale.to_csv('data/salepy.csv', index=False)
#property_type.to_csv('data/property_typepy.csv', index=False)
#lead_type.to_csv('data/lead_typepy.csv', index=False)

In [37]:
are_equal=sale['unit_value'].dropna().equals(sale['actual_value'].dropna())
print(are_equal)

False

In [ ]:
mask = (~sale['unit_value'].isnull()) & (~sale['actual_value'].isnull())

valid_rows = sale[mask]

equal_values = valid_rows['unit_value'] == valid_rows['actual_value']

if equal_values.all():
    print("unit_value is equal to actual_value for all non-null entries.")
else:
    print("unit_value is not equal to actual_value for all non-null entries.")
    print(valid_rows[~equal_values])

unit_value is not equal to actual_value for all non-null entries.
         id  lead_id  unit_value        unit_location  expected_value  \
0     11218   130316  17770000.0            New Cairo             NaN
47     7998   251542   3349446.0       Mostakbal City             NaN
77    11383   389062   5845660.0            New Cairo             NaN
83     6719   203789   1488000.0            New Cairo             NaN
146    9422   305053   6299490.0            New Cairo             NaN
...     ...      ...         ...                  ...             ...
2118   3489   145799   2473073.0      El Sheikh Zayed             NaN
2119   3608   145799   2473073.0      El Sheikh Zayed             NaN
2167  10867   242808  22530000.0  6th of October City             NaN
2179  10367   310033   7204785.0       Mostakbal City       6500000.0
2184   9411   310033   7204785.0       Mostakbal City       6500000.0

      actual_value date_of_reservation reservation_update_date  \
0       17777000.0          2024-01-10     2024-01-10 20:21:00
47       3349540.0          2023-08-01     2023-08-03 00:00:00
77       5908900.0          2024-01-16     2024-01-18 14:48:00
83       2976000.0          2023-04-18                     NaT
146      6746912.0          2023-10-15     2023-10-17 13:58:00
...            ...                 ...                     ...
2118     4946147.0          2022-10-31     2022-10-31 00:00:00
2119     4946147.0          2022-10-31     2022-10-31 00:00:00
2167    45060000.0          2023-12-18                     NaT
2179    14409570.0          2023-10-26     2023-10-29 11:14:00
2184    14409570.0          2023-10-26     2023-10-29 11:14:00

     date_of_contraction  property_type_id  area_id  compound_id  \
0             2024-02-08                21        2          345
47            2023-08-20                21       10          490
77            2024-02-06                21        2          147
83            2023-04-18                21        2          345
146           2023-10-27                21        2          186
...                  ...               ...      ...          ...
2118          2022-11-21                13       26          813
2119          2022-11-21                13       26          813
2167          2023-12-20                 1        1          166
2179          2023-11-29                 3       10          996
2184          2023-11-29                 3       10          996

                  sale_category  years_of_payment
0                       Primary               8.0
47                      Primary               7.0
77                      Primary               8.0
83             Developer Resale               0.0
146                     Primary               8.0
...                         ...               ...
2118  Developer Commercial Sale               7.0
2119  Developer Commercial Sale               7.0
2167                    Primary               7.5
2179                    Primary               8.0
2184                    Primary               8.0

[81 rows x 14 columns]

In [38]:
# Merge the two dataframes on the 'lead_type_id' column
merged_lead = pd.merge(lead, lead_type[['id', 'lead_type']], left_on='lead_type_id', right_on='id', how='left')

# Drop the redundant 'id' column from the right dataframe
merged_lead.drop('id', axis=1, inplace=True)

KeyError: "['id'] not found in axis"

In [41]:
merged_lead1= lead.join(lead_type.set_index('id'), on='lead_type_id', how='left', rsuffix='_lead_type')

In [40]:
merged_lead1

,id,date_of_last_request,buyer,seller,best_time_to_call,budget,created_at,updated_at,user_id,location,...,compound_id,developer_id,meeting_flag,do_not_call,lead_type_id,customer_id,method_of_contact,lead_source,campaign,lead_type
0,9815,2018-09-07 00:00:00,True,False,"All day , any day",NaN,2018-09-07 15:58:00,2024-01-24 15:07:00,2942,Coast 82,...,170,<NA>,<NA>,False,1,22785,form adwords,google,google_cpc,Primary
1,90225,2022-05-04 19:59:00,True,False,NaN,NaN,2022-05-04 19:59:00,2024-01-10 13:10:00,1494,The Waterway North Coast,...,<NA>,<NA>,<NA>,False,1,172065,generic form,google,dev_-_equity,Primary
2,198759,2023-03-22 05:23:00,True,False,NaN,NaN,2023-03-22 05:23:00,2024-02-07 15:45:00,4043,Silversands,...,<NA>,<NA>,<NA>,False,1,192904,whatsapp,google website,NaN,Primary
3,164130,2022-12-14 00:59:00,True,False,NaN,NaN,2022-12-14 00:51:00,2024-01-15 14:38:00,3805,Fouka Bay,...,<NA>,<NA>,<NA>,False,1,112217,facebook,facebook,(none),Primary
4,395907,2024-01-20 17:57:00,True,False,NaN,NaN,2024-01-20 17:57:00,2024-01-22 14:58:00,4003,Golden Eagle,...,<NA>,<NA>,<NA>,False,1,383990,facebook,facebook,madinet nasr for housing and development - lea...,Primary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55919,238383,2023-10-16 17:43:00,True,False,NaN,NaN,2023-06-17 22:45:00,2023-10-17 13:45:00,3806,Address East,...,<NA>,<NA>,<NA>,False,3,231810,phone,phone,p2pwlcrm_bau cell-final-cooing,Resale Buyer
55920,70396,2022-02-04 22:50:00,True,False,NaN,NaN,2022-02-04 22:50:00,2023-07-31 15:13:00,2748,Al Burouj,...,<NA>,<NA>,<NA>,False,1,112626,facebook,facebook,imkan misr - lead generation - cooing 4,Primary
55921,2233,2017-10-04 00:00:00,True,False,NaN,NaN,2017-10-16 10:54:00,2023-12-20 13:41:00,1494,Gouna,...,<NA>,<NA>,<NA>,False,1,68670,facebook,facebook,NaN,Primary
55922,178003,2023-01-22 07:13:00,True,False,NaN,NaN,2023-01-22 07:13:00,2023-01-22 09:29:00,506,Taj City Clubside Apartments,...,<NA>,<NA>,<NA>,False,1,129533,facebook,facebook,madinet nasr for housing and development - lea...,Primary
55923,158781,2022-12-04 10:12:00,True,False,NaN,NaN,2022-12-04 10:12:00,2023-12-31 05:27:00,68,The Med,...,<NA>,<NA>,<NA>,False,1,79875,phone,google,dynamicremarketing,Primary

In [42]:
merged_sale= sale.join(property_type.set_index('id'), on='property_type_id', how='left', rsuffix='_property_type')

In [43]:
merged_sale

,id,lead_id,unit_value,unit_location,expected_value,actual_value,date_of_reservation,reservation_update_date,date_of_contraction,property_type_id,area_id,compound_id,sale_category,years_of_payment,property_type
0,11218,130316,17770000.0,New Cairo,NaN,17777000.0,2024-01-10,2024-01-10 20:21:00,2024-02-08,21,2,345,Primary,8.0,Apartment
1,776,32565,648000.0,New Capital City,NaN,NaN,2021-04-11,NaT,NaT,8,9,464,NaN,NaN,Office
2,3016,20428,8912000.0,6th October,NaN,8912000.0,2022-09-04,2022-09-05 00:00:00,2022-10-23,1,1,402,Primary,NaN,Villa
3,9305,312091,3658000.0,Mostakbal City,NaN,3658000.0,2023-10-12,NaT,2023-10-12,13,10,908,Developer Commercial Sale,10.0,Clinic
4,11885,173993,NaN,New Cairo,10000000.0,NaN,NaT,NaT,NaT,21,2,1116,NaN,NaN,Apartment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2189,9722,323644,10295046.0,Mostakbal City,9938721.0,NaN,2023-10-31,2023-11-02 09:19:00,2023-11-21,3,10,996,Primary,8.0,Duplex
2190,9499,311659,2640000.0,New Capital City,2640000.0,NaN,2023-10-22,NaT,2023-10-29,8,9,1056,Developer Commercial Sale,10.0,Office
2191,3490,145565,3824000.0,6th of October City,3842000.0,3824000.0,2022-10-30,NaT,2022-12-07,20,1,822,Primary,9.0,Serviced Apartment
2192,3670,145565,1200000.0,New Cairo,NaN,1200000.0,2022-11-15,NaT,2022-12-04,20,2,371,Primary,6.0,Serviced Apartment
2193,3671,145565,1200000.0,New Cairo,NaN,1200000.0,2022-11-15,NaT,2022-12-04,20,2,371,Primary,6.0,Serviced Apartment

In [42]:
merged_sale_lead = sale.join(lead.drop(columns=['id']), on='lead_id', rsuffix='_lead')

In [43]:
merged_sale_lead

,id,lead_id,unit_value,unit_location,expected_value,actual_value,date_of_reservation,reservation_update_date,date_of_contraction,property_type_id,...,area_id_lead,compound_id_lead,developer_id,meeting_flag,do_not_call,lead_type_id,customer_id,method_of_contact,lead_source,campaign
0,11218,130316,17770000.0,New Cairo,NaN,17777000.0,2024-01-10,2024-01-10 20:21:00,2024-02-08,21,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
1,776,32565,648000.0,New Capital City,NaN,NaN,2021-04-11,NaT,NaT,8,...,<NA>,<NA>,<NA>,<NA>,False,1.0,331576.0,facebook,facebook,sodic - lead generation - cooing 7
2,3016,20428,8912000.0,6th October,NaN,8912000.0,2022-09-04,2022-09-05 00:00:00,2022-10-23,1,...,<NA>,<NA>,<NA>,<NA>,False,1.0,3125.0,facebook,facebook,ora developers - lead generation - new - cooing 2
3,9305,312091,3658000.0,Mostakbal City,NaN,3658000.0,2023-10-12,NaT,2023-10-12,13,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
4,11885,173993,NaN,New Cairo,10000000.0,NaN,NaT,NaT,NaT,21,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2189,9722,323644,10295046.0,Mostakbal City,9938721.0,NaN,2023-10-31,2023-11-02 09:19:00,2023-11-21,3,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
2190,9499,311659,2640000.0,New Capital City,2640000.0,NaN,2023-10-22,NaT,2023-10-29,8,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
2191,3490,145565,3824000.0,6th of October City,3842000.0,3824000.0,2022-10-30,NaT,2022-12-07,20,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
2192,3670,145565,1200000.0,New Cairo,NaN,1200000.0,2022-11-15,NaT,2022-12-04,20,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
2193,3671,145565,1200000.0,New Cairo,NaN,1200000.0,2022-11-15,NaT,2022-12-04,20,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
#merged_sale_lead.to_csv('data/merged_sale_lead.csv', index=False)

In [44]:
#merged_lead1.to_csv('data/merged_lead1.csv', index=False)
#merged_sale.to_csv('data/merged_sale.csv', index=False)